laravel:
    container_name: ihs_laravel
    build: .
    volumes:
        - ./www/:/www
    #restart: always
nginx:
    container_name: ihs_nginx
    image: nginx:1.10-alpine
    ports:
        - "8080:8080"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites/:/etc/nginx/sites-enabled:ro
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./nginx/logs/:/logs
    volumes_from:
        - laravel
    links:
        - laravel
    #restart: always
