laravel:
    container_name: ihs_laravel
    build: .
    volumes:
        - ./www/:/www
    links:
        - mariadb
    #restart: always
nginx:
    container_name: ihs_nginx
    image: nginx:1.10-alpine
    ports:
        - "80:8080"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites/:/etc/nginx/sites-enabled:ro
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./nginx/logs/:/logs
    volumes_from:
        - laravel
    links:
        - laravel
    #restart: always
mariadb:
    container_name: ihs_mariadb
    image: mariadb:10.1
    env_file: ./www/.env
    environment:
        # Fix https://goo.gl/fUTycl
        MYSQL_HOST:
    ports:
        - "3306:3306"
    #restart: always
